import fs from 'node:fs';
import { MongoClient } from 'mongodb';
const env = Object.fromEntries(fs.readFileSync('.env.local','utf8').split('\n').filter(l=>/^[A-Z_]+=/.test(l)).map(l=>[l.slice(0,l.indexOf('=')), l.slice(l.indexOf('=')+1).trim()]));
const c = new MongoClient(env.MONGODB_URI,{serverSelectionTimeoutMS:15000}); await c.connect();
const db = c.db('imgcreate');
console.log('--- house_rules ---');
for (const r of await db.collection('house_rules').find({}).sort({order:1}).toArray()) console.log(r.order, r.critical?'★':' ', r.kr);
console.log('--- products fields ---');
const p = await db.collection('products').find({}).toArray();
console.log(Object.keys(p[0]).join(','));
console.log(p.map(x=>`${x.line}(${x.colors.length}) ratio=${x.ratio} rec="${x.recommendedModels}" same=${x.sameShapeAs||'-'}`).join('\n'));
const colorTotal = p.reduce((a,x)=>a+x.colors.length,0);
console.log('color slots:', colorTotal, 'with elementId:', p.flatMap(x=>x.colors).filter(c=>c.elementId).length, 'with sprite360:', p.flatMap(x=>x.colors).filter(c=>c.sprite360).length, 'with labOffset:', p.flatMap(x=>x.colors).filter(c=>c.labOffset).length);
console.log('--- product_items line null ---');
const pi = await db.collection('product_items').find({}).toArray();
console.log('total',pi.length,'line=null',pi.filter(x=>!x.line).length,'colorKey=null',pi.filter(x=>!x.colorKey).length);
console.log('fields:',Object.keys(pi[0]).join(','));
console.log('categories:', JSON.stringify(pi.reduce((a,x)=>{a[x.category||'(빈)']=(a[x.category||'(빈)']||0)+1;return a;},{})));
console.log('--- cuts by line ---');
const cu = await db.collection('cuts').find({}).toArray();
console.log(JSON.stringify(cu.reduce((a,x)=>{a[x.line]=(a[x.line]||0)+1;return a;},{})));
console.log('hidden:',cu.filter(x=>x.hidden).length,'with prompt:',cu.filter(x=>x.prompt).length,'with inputImages:',cu.filter(x=>x.inputImages).length,'source imgcreate:',cu.filter(x=>x.source==='imgcreate').length);
console.log('--- size_presets ---');
for (const s of await db.collection('size_presets').find({}).sort({order:1}).toArray()) console.log(s.value, s.group, s.label);
console.log('--- variation_options axes ---');
const vo = await db.collection('variation_options').find({}).toArray();
console.log(JSON.stringify(vo.reduce((a,x)=>{a[x.axis]=(a[x.axis]||0)+1;return a;},{})));
console.log(vo.map(v=>v.axis+':'+v.value).join(' | '));
console.log('--- talents fields ---');
const t = await db.collection('talents').find({}).toArray();
console.log(Object.keys(t[0]).join(','));
console.log(t.map(x=>`${x.code} ${x.size} outfits=${x.outfits.length}`).join('\n'));
console.log('--- pose_refs tags/lines ---');
const pr = await db.collection('pose_refs').find({}).toArray();
console.log(JSON.stringify(pr.reduce((a,x)=>{a[x.line]=(a[x.line]||0)+1;return a;},{})));
console.log('tags:',JSON.stringify([...new Set(pr.map(x=>x.tag))]));
console.log('fields:',Object.keys(pr[0]).join(','));
console.log('--- color_chips fields ---');
const cc = await db.collection('color_chips').find({}).toArray();
console.log(Object.keys(cc[0]).join(','), JSON.stringify(cc[0]));
await c.close();
