import fs from 'node:fs';
import { MongoClient } from 'mongodb';
const Y='C:/Users/Yogibo Design/Desktop/youtube';
const env = Object.fromEntries(fs.readFileSync('.env.local','utf8').split('\n').filter(l=>/^[A-Z_]+=/.test(l)).map(l=>[l.slice(0,l.indexOf('=')), l.slice(l.indexOf('=')+1).trim()]));
const c = new MongoClient(env.MONGODB_URI,{serverSelectionTimeoutMS:15000}); await c.connect();
const db=c.db('imgcreate');
const cuts = await db.collection('cuts').find({}).toArray();
const norm=u=>String(u).split('?')[0];
const inDb = new Set(cuts.map(x=>norm(x.url)));
const urls = JSON.parse(fs.readFileSync(Y+'/cut_urls.json','utf8'));
const uniq=[...new Set(urls.map(norm))];
console.log('cut_urls unique',uniq.length,'db unique',inDb.size);
const missing = uniq.filter(u=>!inDb.has(u));
console.log('IN cut_urls NOT in db:', missing.length);
console.log(missing.map(u=>u.split('/').pop()).join('\n'));
const extra=[...inDb].filter(u=>!new Set(uniq).has(u));
console.log('IN db NOT in cut_urls:', extra.length);
console.log(extra.map(u=>u.split('/').pop()).slice(0,40).join('\n'));
await c.close();
