import fs from 'node:fs';
import { MongoClient } from 'mongodb';
const env = Object.fromEntries(fs.readFileSync('.env.local','utf8').split('\n').filter(l=>/^[A-Z_]+=/.test(l)).map(l=>[l.slice(0,l.indexOf('=')), l.slice(l.indexOf('=')+1).trim()]));
const c = new MongoClient(env.MONGODB_URI); await c.connect(); const db=c.db('imgcreate');
console.log('-- variation_options full --');
(await db.collection('variation_options').find({}).sort({axis:1,order:1}).toArray()).forEach(v=>console.log(`${v.axis}/${v.value} | ${v.label} | hint="${v.hint}"`));
console.log('\n-- products color keys per line --');
(await db.collection('products').find({}).sort({order:1}).toArray()).forEach(p=>console.log(p.line, p.emoji, '|', p.spec, '| colors:', p.colors.map(x=>`${x.key}${x.views?'(v)':''}${x.elementId?'(E)':''}`).join(',')));
console.log('\n-- distinct expressions in cuts --');
console.log(await db.collection('cuts').distinct('recipe.expression'));
console.log('-- distinct poses in cuts --');
console.log(await db.collection('cuts').distinct('recipe.pose'));
console.log('-- distinct outfits in cuts --');
console.log(await db.collection('cuts').distinct('recipe.outfit'));
console.log('\n-- color_chips --');
(await db.collection('color_chips').find({}).toArray()).forEach(x=>console.log(x.id, x.hex, x.name, '|', x.note));
await c.close();
