import fs from 'node:fs';
import { MongoClient } from 'mongodb';
const env = Object.fromEntries(fs.readFileSync('.env.local','utf8').split('\n').filter(l=>/^[A-Z_]+=/.test(l)).map(l=>[l.slice(0,l.indexOf('=')), l.slice(l.indexOf('=')+1).trim()]));
const c = new MongoClient(env.MONGODB_URI); await c.connect(); const db=c.db('imgcreate');
const prods = await db.collection('products').find({}).toArray();
let slots=0, withEl=0, withViews=0, withSprite=0, withLab=0;
for (const p of prods) for (const col of p.colors) { slots++;
  if(col.elementId) withEl++; if(col.views) withViews++; if(col.sprite360) withSprite++; if(col.labOffset) withLab++; }
console.log('color slots', slots, 'elementId', withEl, 'views', withViews, 'sprite360', withSprite, 'labOffset', withLab);
console.log('lines:', prods.map(p=>`${p.line}(${p.colors.length})`).join(' '));
console.log('\n-- pose_refs per line --');
const pr = await db.collection('pose_refs').find({}).toArray();
const byLine={}; pr.forEach(p=>byLine[p.line]=(byLine[p.line]||0)+1); console.log(byLine);
console.log('sample notes:', pr.slice(0,6).map(p=>p.key+' | '+p.name+' | '+p.note).join('\n'));
console.log('\n-- talents outfits --');
const ts = await db.collection('talents').find({}).toArray();
ts.forEach(t=>console.log(t.code, t.slot, '|', t.size, '| outfits:', t.outfits.map(o=>o.code).join(',')));
console.log('\n-- size_presets --');
(await db.collection('size_presets').find({}).toArray()).forEach(s=>console.log(s.value, s.group, s.label, s.genAspect, s.retention));
console.log('\n-- variation axes --');
const vo = await db.collection('variation_options').find({}).toArray();
const ax={}; vo.forEach(v=>{(ax[v.axis]??=[]).push(v.value)}); console.log(ax);
console.log('\n-- usage_shots kinds --');
const us = await db.collection('usage_shots').find({}).toArray();
const k={}; us.forEach(u=>k[u.kind]=(k[u.kind]||0)+1); console.log(k);
console.log('lines covered:', [...new Set(us.map(u=>u.line))]);
console.log('\n-- cuts sample recipes --');
(await db.collection('cuts').find({}).limit(5).toArray()).forEach(x=>console.log(x.line, x.colorKey, '|', x.spec, '|', JSON.stringify(x.recipe)));
const hid = await db.collection('cuts').countDocuments({hidden:true});
console.log('hidden cuts:', hid);
console.log('\n-- house rules --');
(await db.collection('house_rules').find({}).toArray()).forEach(r=>console.log(r.critical?'★':' ', r.kr.slice(0,60)));
await c.close();
